---
output:
  pdf_document: default
  html_document: default
---

# Introduction

**Background of the Senior Executive Service (SES) Program**

The Senior Executive Service (SES) was established by the Civil Service Reform Act (CSRA) in 1978. The introduction of the CSRA is to select and develop high-level executives corps with exceptional management skills. Members of the SES, granted with high authority, not only ensure productivity and efficiency within the government but also provide leadership to agencies across administration. Each executive holds key position below the top political appointees, and serves as primary link between these appointees and government career workers. [@SES2017]
\hfill\break

Before the existence of the SES, the federal government was a fragmented bureaucracy. The creation of these centralized senior leaders therefore brings a “measure of coherence” to fulfil the larger corporate interests of the federal government. [@carey2011senior] With more than thirty years of establishment, the SES becomes “the backbone of Federal executive leadership", where its members "play a crucial role in addressing unprecedented challenges facing our nation.” [@congress2011]
\hfill\break

The Office of Personnel Management (OPM), also established by the CSRA, is tasked to manage the overall SES program. Currently, there are four types of appointments in the SES. The first type is career appointment, where incumbents are selected through merit-based staffing and usually hold permanent position within the government. The other three types are either non-career appointment or appointment with limited terms. Since the majority of positions in the SES is made up of career appointments, the primary interest of this study would focus on career track SES.
\hfill\break

**Challenges of the SES Program**

The selection process of the SES is usually rigorous. Currently, the selection of career appointment in the SES is based on OPM’s Executive Core Qualifications (ECQ), which specifies a candidate’s competencies to build successful teams and bring out strategic integration within and outside the organization. Specifically, the OPM identifies various critical leadership skills for executives to succeed. For example, executives need to have the abilities to lead strategic changes and achieve organizational goals with high-quality results. The approval of a candidate is further reviewed by Qualifications Review Boards (QRBs), consisting of three SES members from distinct agencies.
\hfill\break

While the recruiting of the SES position consists of multiple phases, the effectiveness of the SES recruiting is doubtful. For example, promotion bias towards people with technical expertise existed in the early establishment of the SES program. Furthermore, some of the outside observers have raised concern about the diversity of the SES. As a result, various studies have been conducted on the current SES system. For example, Powell and Butterfield investigated the impact of gender on the promotion decisions of the SES positions. [@powell1994investigating] Shafritz argued that the quality of the SES can be improved with more racial, ethnic and gender diversity. [@carey2011senior]
\hfill\break

**Goal of the study**

The motivation behind this project is twofold: first, to understand what factors influence the promotion outcome of the SES positions, and second, to delve into the gender and racial diversity of the SES recruiting.