---
author: 'Jerry Chia-Rui Chang'
date: 'May 2018'
institution: 'Duke University'
division: 'Trinity College of Arts and Sciences'
advisor: 'Jerome P. Reiter'
committeememberone: 'Committeemember O. Name'
committeemembertwo: 'Committeemember T. Name'
dus: 'Mine Cetinkaya-Rundel'
department: 'Department of Statistical Science'
degree: 'Bachelor of Science in Statistical Science'
title: 'Modeling of Missing Data'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  #thesisdowndss::thesis_pdf: default
  thesisdowndss::thesis_gitbook: default
  #thesisdowndss::thesis_word: default
  #thesisdowndss::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.
acknowledgements: |
  I want to thank a few people.
dedication: |
  You can have a dedication here if you wish. 
preface: |
  This is an example of a thesis setup to use the reed thesis document class
  (for LaTeX) and the R bookdown package, in general.
bibliography: bib/thesis.bib
# Refer to your specific bibliography file in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
#space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdowndss package is
# installed and loaded. This thesisdowndss package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdowndss))
  devtools::install_github("mine-cetinkaya-rundel/thesisdowndss")
library(thesisdowndss)
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Abstract {.unnumbered}

The Senior Executive Service (SES) hold key leadership positions across agencies within the Federal government. These leaders serve as the primary link between top political appointees and the rest of the Federal workforce. The selection of career-reserved SES, often considered as lack of diversity, possesses great challenges to an effective SES program. Therefore, this study aims to understand factors that impact the SES promotion outcome, where data about federal employees' personal and career information would be analyzed.

Due to recording error and time constraints, multiple variables have missing data, with some over 80% missing. To address potential data analysis challenges caused by missing data, we adopt Multiple Imputation techniques to impute missing data. First, multiple completed datasets are generated through Multivariate Imputation by Chained Equations (MICE), where Classification and Regression Tree (CART) is specified as the conditional distribution. Posterior Predictive Check (PPC) is then applied to check the robustness of the model. Second, we fit a semi-parametric spline logistic regression model on one completed dataset. The model coefficients are estimated by two approaches - Frequentist's maximum likelihood and Bayesian's posterior distribution. Lastly, we combine each completed dataset's analysis, where inference is conducted on the combined model results.